name: deploy-ci
on:
  push:
    branches:
      - dev
jobs:
  main:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: build and push to docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./DockerFile
          context: .
          tags: ${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

    