name: deploy
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: build and push to docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          secrets: [
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} ,DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}]
          tags: [${{ github.sha }}]

    